# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hello/Downloads/TIFR/300mhz_testing-20210724T133626Z-001/300mhz_testing/fine_counter_testing/fine_counter_testing.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hello/Downloads/TIFR/300mhz_testing-20210724T133626Z-001/300mhz_testing/fine_counter_testing/fine_counter_testing.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hello/Downloads/TIFR/300mhz_testing-20210724T133626Z-001/300mhz_testing/fine_counter_testing/fine_counter_testing.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/hello/Downloads/TIFR/300mhz_testing-20210724T133626Z-001/300mhz_testing/fine_counter_testing/fine_counter_testing.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hello/Downloads/TIFR/300mhz_testing-20210724T133626Z-001/300mhz_testing/fine_counter_testing/fine_counter_testing.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hello/Downloads/TIFR/300mhz_testing-20210724T133626Z-001/300mhz_testing/fine_counter_testing/fine_counter_testing.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
